if(EXISTS "/Users/dominikpanzarella/Desktop/tsp-meta-solver/build-release/backend/tsp_tests[1]_tests.cmake")
  include("/Users/dominikpanzarella/Desktop/tsp-meta-solver/build-release/backend/tsp_tests[1]_tests.cmake")
else()
  add_test(tsp_tests_NOT_BUILT tsp_tests_NOT_BUILT)
endif()
